const WORDS = [
  { id: "VULN-001", term: "Consequently", definition: "As a result; therefore.", example: "The endpoint did not check ownership. Consequently, any user could view invoices that were not theirs." },
  { id: "VULN-002", term: "Catastrophic", definition: "Worst-case severity. Total compromise, not just a minor issue.", example: "A missing check on the admin panel made the bug catastrophic." },
  { id: "VULN-003", term: "Discretion", definition: "Freedom to decide something based on personal judgment.", example: "The bounty amount was left to the program's discretion." },
  { id: "VULN-004", term: "Hierarchy", definition: "A ranked system, usually ordered from highest to lowest authority.", example: "The role hierarchy runs admin, then manager, then user." },
  { id: "VULN-005", term: "Windfall", definition: "A large, unexpected gain, often financial.", example: "A critical finding on a major program was a windfall." },
  { id: "VULN-006", term: "Substantial", definition: "Large in amount, size, or importance.", example: "The report showed substantial impact across all customer accounts." },
  { id: "VULN-007", term: "Hurdle", definition: "An obstacle that must be overcome.", example: "NIC verification is the hurdle before the balance can be withdrawn." },
  { id: "VULN-008", term: "Seamless", definition: "Smooth, with no visible breaks or friction.", example: "A seamless checkout flow should never expose a token in the URL." },
  { id: "VULN-009", term: "Despite", definition: "In spite of; regardless of.", example: "Despite the payout cut, the private tier still pays well." },
  { id: "VULN-010", term: "Watershed moment", definition: "A turning point marking a real before-and-after shift.", example: "The first accepted report was a watershed moment for the whole plan." },
  { id: "VULN-011", term: "Inflation", definition: "A general rise in prices over time. In security, severity inflation means rating a bug higher than it deserves.", example: "The triager pushed back on the severity, calling it inflation." },
  { id: "VULN-012", term: "Convoluted", definition: "Needlessly complex, tangled, hard to follow.", example: "A convoluted five-step permission check is exactly where logic bugs hide." },
  { id: "VULN-013", term: "Diverge", definition: "To split off from an expected path; to differ.", example: "The bug exists exactly where the implementation diverges from intended behavior." },
  { id: "VULN-014", term: "Data pipeline", definition: "An automated sequence that moves and transforms data from one system to another.", example: "The recon results flow through a data pipeline before hitting the database." },
  { id: "VULN-015", term: "Lucrative", definition: "Producing a lot of profit.", example: "Private programs are usually more lucrative than public ones." },
  { id: "VULN-016", term: "Attrition", definition: "The rate at which people leave something over time.", example: "High researcher attrition on a program often means low payouts." },
  { id: "VULN-017", term: "Collision", definition: "Two things happening or landing on the same point at once.", example: "Two hunters reporting the same bug within hours causes a duplicate collision." },
  { id: "VULN-018", term: "Astronomical", definition: "Extremely large in scale.", example: "The RCE payout was astronomical compared to a normal finding." },
  { id: "VULN-019", term: "SSL configuration warning", definition: "An alert flagging a weak, expired, or misconfigured TLS/SSL certificate setup.", example: "The browser threw an SSL configuration warning on the staging subdomain." },
  { id: "VULN-020", term: "Arteries", definition: "Core pathways something flows through, used as a metaphor for main routes or channels.", example: "The main API arteries of the app all route through one auth service." },
  { id: "VULN-021", term: "Hostile", definition: "Actively adversarial or threatening.", example: "The IP range was flagged as hostile by threat intelligence feeds." },
  { id: "VULN-022", term: "Paradigm", definition: "A typical pattern or model of how something works.", example: "Zero trust is a different security paradigm than perimeter defense." },
  { id: "VULN-023", term: "Compensated", definition: "Paid or rewarded, usually financially.", example: "The researcher was compensated for the verified critical finding." },
  { id: "VULN-024", term: "Meticulously", definition: "With great, careful attention to detail.", example: "The report documented every step meticulously." },
  { id: "VULN-025", term: "Minified", definition: "Code compressed by stripping whitespace and comments to shrink file size.", example: "The minified JavaScript file still leaked an API key in a string." },
  { id: "VULN-026", term: "Residential ISP", definition: "An internet provider serving home users, as opposed to datacenter or hosting IP ranges.", example: "Traffic from a residential ISP raises less suspicion than a known VPS range." },
  { id: "VULN-027", term: "Hypervisor", definition: "Software that creates and manages virtual machines on physical hardware.", example: "A hypervisor escape would let an attacker break out of one VM into the host." },
  { id: "VULN-028", term: "Multiplexer", definition: "A tool that lets multiple sessions or signals run through one channel.", example: "tmux is a terminal multiplexer that keeps sessions alive after disconnecting." },
  { id: "VULN-029", term: "Sole proprietorship", definition: "The simplest legal business structure, where one person owns the business and is personally liable.", example: "A sole proprietorship has less paperwork but no liability protection." },
  { id: "VULN-030", term: "Counterintuitive", definition: "The opposite of what you would expect.", example: "It felt counterintuitive, but the read-only endpoint was the dangerous one." },
  { id: "VULN-031", term: "Fiercest", definition: "Most intense or aggressive.", example: "Competition is fiercest on programs that have been public for years." },
  { id: "VULN-032", term: "Tenet", definition: "A core belief or principle someone holds as true.", example: "Verify before you trust is a basic tenet of testing AI claims." },
  { id: "VULN-033", term: "Sunk cost", definition: "Money or time already spent that cannot be recovered and should not influence future decisions.", example: "Ignoring the sunk cost, he dropped the target after twelve hours with nothing found." },
  { id: "VULN-034", term: "Mandate", definition: "An official requirement or order.", example: "The program has a mandate requiring two-factor authentication on all accounts." },
  { id: "VULN-035", term: "Verbose", definition: "Using more words or detail than necessary.", example: "The verbose error message leaked the full stack trace." },
  { id: "VULN-036", term: "Conceivable", definition: "Able to be imagined or believed possible.", example: "It is conceivable that the two bugs could be chained together." },
  { id: "VULN-037", term: "Outright", definition: "Complete, total, without qualification.", example: "The endpoint had no authorization check at all, an outright failure." },
  { id: "VULN-038", term: "Agentic risk", definition: "A risk specific to AI systems that can autonomously take actions or use tools.", example: "Prompt injection that triggers a tool call is a classic agentic risk." },
  { id: "VULN-039", term: "Acutely", definition: "Sharply, intensely.", example: "The team was acutely aware of the deadline." },
  { id: "VULN-040", term: "Regurgitating", definition: "Repeating information back without real understanding of it.", example: "Reading the definition once is just regurgitating it, not learning it." },
  { id: "VULN-041", term: "Monolithic scanner", definition: "A single large all-in-one tool that tries to handle every task, as opposed to small modular tools.", example: "He replaced the monolithic scanner with a chain of focused single-purpose tools." },
  { id: "VULN-042", term: "Adversarial", definition: "Opposing, actively working against something.", example: "Red teaming takes an adversarial approach to test real defenses." },
  { id: "VULN-043", term: "Orchestrator", definition: "Someone or something that directs and coordinates multiple parts.", example: "In the future the hunter may act as the orchestrator of a team of AI agents." },
  { id: "VULN-044", term: "Inclusion", definition: "The act of being included. In security, file inclusion bugs let an attacker load unintended files into an app.", example: "Local File Inclusion let the attacker read files outside the intended folder." },
  { id: "VULN-045", term: "Pristine", definition: "Perfectly clean, untouched, in original condition.", example: "The test account was left in a pristine state before the exploit began." },
  { id: "VULN-046", term: "Pinnacle", definition: "The highest point, the peak of achievement.", example: "Landing a critical on a top private program is the pinnacle of the hunt." },
  { id: "VULN-047", term: "Unglamorous", definition: "Not exciting or impressive-looking, though often necessary.", example: "Logging dropped targets is unglamorous work that pays off later." },
  { id: "VULN-048", term: "Tedious", definition: "Long, repetitive, and boring.", example: "Building the full coverage matrix was tedious but thorough." },
  { id: "VULN-049", term: "Brittle", definition: "Easily broken; fragile, especially under small changes.", example: "The authorization check was brittle and broke as soon as the parameter order changed." },
  { id: "VULN-050", term: "Scrutiny", definition: "Close, careful examination.", example: "The report held up under the triager's scrutiny." },
  { id: "VULN-051", term: "Plummet", definition: "To drop suddenly and sharply.", example: "Response rates plummet on programs that get flooded with low-quality reports." },
  { id: "VULN-052", term: "Anomalous", definition: "Deviating from what is normal or expected.", example: "The scanner flagged anomalous traffic coming from a single account." },
  { id: "VULN-053", term: "Constitutional", definition: "Relating to a fundamental set of rules or principles something is built on.", example: "Constitutional AI is a training approach built around a fixed set of guiding principles." }
];
